// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudTrabajoBimestral.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250519212012_v01")]
    partial class v01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaAsistencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("inscripcionId")
                        .HasColumnType("int");

                    b.Property<int>("sesionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("inscripcionId");

                    b.HasIndex("sesionId");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Certificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InscripcionID")
                        .HasColumnType("int");

                    b.Property<string>("UrlDescarga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaEmision")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionID");

                    b.ToTable("Certificado");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Espacio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Espacio");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<string>("ParticipanteCedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaInscripcion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("ParticipanteCedula");

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InscripcionID")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("medioPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("monto")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionID");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Participante", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cedula");

                    b.ToTable("Participante");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Ponente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ponente");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EspacioID")
                        .HasColumnType("int");

                    b.Property<int>("EventoID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("horaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("horaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EspacioID");

                    b.HasIndex("EventoID");

                    b.ToTable("Sesion");
                });

            modelBuilder.Entity("PonenteSesion", b =>
                {
                    b.Property<int>("PonentesId")
                        .HasColumnType("int");

                    b.Property<int>("SesionesId")
                        .HasColumnType("int");

                    b.HasKey("PonentesId", "SesionesId");

                    b.HasIndex("SesionesId");

                    b.ToTable("PonenteSesion");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Asistencia", b =>
                {
                    b.HasOne("CloudTrabajoBimestral.Models.Inscripcion", "Inscripcion")
                        .WithMany("Asistencias")
                        .HasForeignKey("inscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudTrabajoBimestral.Models.Sesion", "Sesion")
                        .WithMany("Asistencias")
                        .HasForeignKey("sesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Certificado", b =>
                {
                    b.HasOne("CloudTrabajoBimestral.Models.Inscripcion", "Inscripcion")
                        .WithMany("Certificados")
                        .HasForeignKey("InscripcionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Inscripcion", b =>
                {
                    b.HasOne("CloudTrabajoBimestral.Models.Evento", null)
                        .WithMany("Inscripciones")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudTrabajoBimestral.Models.Participante", "Participante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ParticipanteCedula");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Pago", b =>
                {
                    b.HasOne("CloudTrabajoBimestral.Models.Inscripcion", "Inscripcion")
                        .WithMany("Pagos")
                        .HasForeignKey("InscripcionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Sesion", b =>
                {
                    b.HasOne("CloudTrabajoBimestral.Models.Espacio", "Espacio")
                        .WithMany("Sesiones")
                        .HasForeignKey("EspacioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudTrabajoBimestral.Models.Evento", "Evento")
                        .WithMany("Sesion")
                        .HasForeignKey("EventoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espacio");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("PonenteSesion", b =>
                {
                    b.HasOne("CloudTrabajoBimestral.Models.Ponente", null)
                        .WithMany()
                        .HasForeignKey("PonentesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudTrabajoBimestral.Models.Sesion", null)
                        .WithMany()
                        .HasForeignKey("SesionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Espacio", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Evento", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Inscripcion", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Certificados");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Participante", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("CloudTrabajoBimestral.Models.Sesion", b =>
                {
                    b.Navigation("Asistencias");
                });
#pragma warning restore 612, 618
        }
    }
}
